UPDATE `alpha`.`ref_ship` SET `price_code`='WEEK_SPOT_DIFF', `desc`='SMM铜现货周差' WHERE `id`='221';
update alpha.formula set `formula`=REPLACE(`formula`, 'WEEK_SPOT_RATE','WEEK_SPOT_DIFF')
delete from alpha.formula where id >= 27;
delete from alpha.formula_varieties where formula_id >= 27;
delete from alpha.user_subscription_formula where formula_id >= 27;
INSERT INTO `alpha`.`formula` (`id`, `created_at`, `updated_at`, `formula`, `title`, `description`) VALUES ('27', '2017-08-08 16:36:54', '2017-08-21 11:40:53', 'e_variety = e.ch_variety\nmessage = \"%s合约持仓量和交易量增大, 价格持续下降100元\" % e_variety\n\nopi_data = REF(e, OPI, 3)\nvol_data = REF(e, VOL, 3)\nsettle_data = REF(e, SETTLE, 3)\n\nopi_is_up, opi_up_data = ISCONTUP(opi_data, 0)\nvol_is_up, vol_up_data = ISCONTUP(vol_data, 0)\nsettle_is_down, settle_down_data = ISCONTDOWNABS(settle_data, 100)\n\nif opi_is_up and vol_is_up and settle_is_down:\n    ALERT(e, message)\n    CHART(e, SETTLE)\n\nlogger.info(\"%s合约持仓量增量为:%s,预警值为连续增加, 交易量增量为%s , 预警值为连续增加\"\n            \"结算价下降为%s, 预警幅度为连续下降小于等于100元\",\n            e_variety, opi_up_data, vol_up_data, settle_down_data)', '合约持仓量和交易量增大, 价格持续下降100元', '合约持仓量和交易量增大, 价格持续下降100元');
INSERT INTO `alpha`.`formula` (`id`, `created_at`, `updated_at`, `formula`, `title`, `description`) VALUES ('28', '2017-08-08 16:36:54', '2017-08-21 11:40:53', 'e_variety = e.ch_variety\nmessage = \"%s现货价格价格未动(一天内100元,一周500元), 期货价格持续下跌3天\" % e_variety\n\nspot_week_data = REF(e, WEEK_SPOT_DIFF)[0]\nweek_change = ABS(spot_week_data) <= 500\n\nspot_day_data = REF(e, SPOT, 3)\nday_change, day_change_result = ISCONTCHANGEABS(spot_day_data,100, iseg=False)\n\nsettle_data = REF(e, SETTLE, 3)\n\nsettle_change, change_data = ISCONTDOWNABS(settle_data,0)\n\nif week_change and day_change and settle_change:\n    ALERT(e, message)\n    CHART(e, SETTLE)\n\nlogger.info(\"%s期货价格3天下跌幅度为:%s,预警值为连续下跌, 现货价格一天内改变量为%s元 , \"\n            \"预警幅度为小于等于100元, 现货价格一周内改变是为%s元, 预警值为小于等于500元\",\n            e_variety, change_data, day_change_result, week_change)', '现货价格价格未动(一天内100元,一周500元), 期货价格持续下跌3天', '现货价格价格未动(一天内100元,一周500元), 期货价格持续下跌3天');
INSERT INTO `alpha`.`formula` (`id`, `created_at`, `updated_at`, `formula`, `title`, `description`) VALUES ('29', '2017-08-08 16:36:54', '2017-08-21 11:40:53', 'e_variety = e.ch_variety\nmessage = \"%s现货价格上涨(一天内100元,一周500元), 期货价格持续上升3天\" % e_variety\n\nspot_week_data = REF(e, WEEK_SPOT_DIFF)[0]\nweek_change = ABS(spot_week_data) >= 500\n\nspot_day_data = REF(e, SPOT, 3)\nday_change, day_change_result = ISCONTCHANGEABS(spot_day_data,100)\n\nsettle_data = REF(e, SETTLE, 3)\n\nsettle_change, change_data = ISCONTUPABS(settle_data,0)\n\nif week_change and day_change and settle_change:\n    ALERT(e, message)\n    CHART(e, SPOT)\n\nlogger.info(\"%s期货价格3天上涨幅度为:%s,预警值为连续上涨, 现货价格一天内改变量为%s元 , \"\n            \"预警幅度为大于等于100元, 现货价格一周内改变是为%s元, 预警值为大于等于500元\",\n            e_variety, change_data, day_change_result, week_change)', '现货价格上涨(一天内100元,一周500元), 期货价格持续上升3天', '现货价格上涨(一天内100元,一周500元), 期货价格持续上升3天');
INSERT INTO `alpha`.`formula` (`id`, `created_at`, `updated_at`, `formula`, `title`, `description`) VALUES ('30', '2017-08-08 16:36:54', '2017-08-21 11:40:53', 'e_variety = e.ch_variety\nmessage = \"%s总库存重大变动:连续3天改变2%%\" % e_variety\n\nstock_data = REF(e, STOCK, 3)\nchange, change_data = ISCONTCHANGE(stock_data, 0.02)\n\nALERT(e, message, change)\nCHART(e, STOCK)\n\nlogger.info(\"%s总库存3天改变量为:%s,预警值为连续改变2%%\",\n            e_variety, change_data)', '总库存重大变动:连续3天改变2%', '总库存重大变动:连续3天改变2%');
INSERT INTO `alpha`.`formula` (`id`, `created_at`, `updated_at`, `formula`, `title`, `description`) VALUES ('31', '2017-08-08 16:36:54', '2017-08-21 11:40:53', 'e_variety = e.ch_variety\nmessage = \"%s库存连续改变3天(2%%)而价格未动(一天内100元,一周500元)\" % e_variety\n\nstock_data = REF(e, STOCK, 3)\nis_change, change_result = ISCONTCHANGE(data, 0.02)\n\n\nspot_week_data = REF(e, SPOT, 5, INDEX_CONTRACT)\nweek_change = spot_week_data[-1]-spot_week_data[-5]\nweek_change_result = ABS(week_change) <= 500\n\nspot_day_data = REF(e, SPOT, 3, INDEX_CONTRACT)\nday_change, day_change_result = ISCONTCHANGEABS(spot_day_data,100, iseg=False)\n\nif is_change and week_change and day_change:\n    ALERT(e, message)\n    CHART(e, STOCK)\n\nlogger.info(\"%s库存3天改变量为:%s,预警值为大于等于2%%, 价格一天内改变量为%s元 , \"\n            \"预警幅度为小于等于100元, 价格一周内改变是为%s元, 预警值为小玩等于500元\",\n            e_variety, change_result, day_change_result, week_change)', '库存连续改变3天(2%)而价格未动(一天内100元,一周500元)', '库存连续改变3天(2%)而价格未动(一天内100元,一周500元)');
INSERT INTO `alpha`.`formula` (`id`, `created_at`, `updated_at`, `formula`, `title`, `description`) VALUES ('32', '2017-08-08 16:36:54', '2017-08-21 11:40:53', 'e_variety = e.ch_variety\nmessage = \"%s库存不足\" % e_variety\n\nyear_sale = REF(e, YEAL_SALE, end_date=begin_year())[0]\nstock = REF(e, STOCK)[0]\ndays = stock/(year_sale/365)\n\nalert = days > year_days_remain()\n\nALERT(e, message, alert)\nCHART(e, STOCK)\n\nlogger.info(\"%s库存剩余量为:%s, 按去年平均消费量还可以维持%s天, 今年剩余天数:%s天, \"\n            \"预警值为剩余天数大于可维持天数\",\n            e_variety, days, year_days_remain())', '库存不足以维持剩余天数', '库存不足以维持剩余天数');
ALTER TABLE `alpha`.`main_contract` ADD COLUMN `index_contract` VARCHAR(10) NULL AFTER `serial_contract12`;
INSERT INTO `alpha`.`formula` (`id`, `created_at`, `updated_at`, `formula`, `title`, `description`, `enable`, `unit`) VALUES ('33', '2017-08-08 16:36:54', '2017-08-21 11:40:53', 'e_variety = e.ch_variety\nmessage = \"%s升贴水与上月同期对比差距较大\" % e_variety\n\ne.result = REF(e, PD_MONTH_DIFF)\n\ndiff = e.result[0]\n\nni_alert = e.content_variety == Ni and diff >= 300\nother_alert = e.content_variety != Ni and diff >= 100\n\nalert =  ni_alert or other_alert\n\nCHART(e, PD)\nALERT(e, message, alert)\n\nlogger.info(\"%s升贴水与上月同期对比差距:%s, 预警为镍:300, 其它100\", e_variety, diff)', '升贴水与上月同期对比差距较大', '升贴水与上月同期对比差距较大', '1', '元');

update alpha.main_contract set index_contract = CONCAT(varieties, '8888') where index_contract is null;
update alpha.main_contract set main_contract = CONCAT(varieties, '9999') where main_contract = '' and settlement_date < '2015-12-31';
UPDATE `alpha`.`ref_ship` SET `price_code`='WEEK_SPOT_DIFF' WHERE `id`='221';